routes:
  /: home
  /glossary/:
    controller: channel
    filter:     primary_tag:glossary
    order:      title asc
    permalink:  /glossary/{slug}/
    template:   tag
  /languages/:
    controller: channel
    filter:     primary_tag:languages
    order:      title asc
    permalink:  /languages/{slug}/
    template:   tag
  /reviews/:
    controller: channel
    filter:     primary_tag:reviews
    permalink:  /reviews/{slug}/
    template:   tag

collections:
  /blog/:
    permalink: /blog/{slug}/

taxonomies:
  tag: /tags/{slug}/