routes:
  /: home

collections:
  /blog/:
    filter:    primary_tag:blog
    permalink: /blog/{slug}/
    template:  tag
  /glossary/:
    filter:    primary_tag:glossary
    order:     title asc
    permalink: /glossary/{slug}/
    template:  tag
  /languages/:
    filter:    primary_tag:languages
    order:     title asc
    permalink: /languages/{slug}/
    template:  tag
  /reviews/:
    filter:    primary_tag:reviews
    permalink: /reviews/{slug}/
    template:  tag

taxonomies:
  tag: /tags/{slug}/