301:
  ^\/glossary\/([a-z0-9-]+)\/$: /encyclopedia/$1
302:
  /books:          https://www.amazon.com/shop/linguisticdiscovery
  /glossary:       /encyclopedia
  /podcasts:       https://resources.linguisticdiscovery.com/Podcasts-fb588d41dda146eea501ed9f23975ce6
  /world-of-words: /newsletter