301:
  ^\/blog\/([a-z0-9-]+)\/$:         /posts/$1
  ^\/encyclopedia\/([a-z0-9-]+)\/$: /posts/$1
  ^\/glossary\/([a-z0-9-]+)\/$:     /posts/$1
  ^\/reviews\/([a-z0-9-]+)\/$:      /posts/$1
302:
  /blog:           /posts
  /books:          https://www.amazon.com/shop/linguisticdiscovery
  /conventions:    https://resources.linguisticdiscovery.com/Conventions-23650a282bc1803c99cad1e934036a64
  /digest:         /current-linguistics
  /glossary:       /encyclopedia
  /newsletter:     /articles
  /podcasts:       https://resources.linguisticdiscovery.com/Podcasts-fb588d41dda146eea501ed9f23975ce6
  /resources:      https://resources.linguisticdiscovery.com/
  /world-of-words: /articles