routes:
  /: home
  /posts/:
    controller: channel
    filter:
    permalink:  /posts/{slug}/
    template:   index

collections:
  /blog/:
    filter:     primary_tag:blog
    permalink:  /blog/{slug}/
    template:   index
  /encyclopedia/:
    filter:     primary_tag:encyclopedia
    order:      title asc
    permalink:  /encyclopedia/{slug}/
    template:   tag
  /languages/:
    filter:     primary_tag:languages
    order:      title asc
    permalink:  /languages/{slug}/
    template:   tag
  /newsletter/:
    data:       tag.newsletter
    filter:     primary_tag:newsletter
    order:      title desc
    permalink:  /newsletter/{slug}/
    template:   tag
  /reviews/:
    filter:     primary_tag:reviews
    permalink:  /reviews/{slug}/
    template:   tag

taxonomies:
  tag: /tags/{slug}/