routes:
  /: home
  /digest/:
    controller: channel
    data:       tag.digest
    filter:     tag:digest
    template:   tag
  /encyclopedia/:
    controller: channel
    data:       tag.encyclopedia
    filter:     tag:encyclopedia
    order:      title asc
    template:   index
  /languages/:
    controller: channel
    data:       tag.languages
    filter:     tag:languages
    order:      title asc
    template:   index
  /newsletter/:
    controller: channel
    data:       tag.newsletter
    filter:     tag:newsletter
    template:   tag
  /reviews/:
    controller: channel
    data:       tag.reviews
    filter:     tag:reviews
    template:   index
  /sitemap/:
    template:     sitemap
    content_type: text/xml

collections:
  /posts/:
    permalink: /posts/{slug}/
    template:  index

taxonomies:
  tag: /tags/{slug}/