routes:
  /: home
  /encyclopedia/:
    controller: channel
    data:       tag.encyclopedia
    filter:     tag:encyclopedia
    order:      title asc
    template:   index
  /languages/:
    controller: channel
    data:       tag.languages
    filter:     tag:languages
    order:      title asc
    template:   index
  /reviews/:
    controller: channel
    data:       tag.reviews
    filter:     tag:reviews
    template:   index

collections:
  /digest/:
    data:      tag.digest
    filter:    tag:digest
    permalink: /digest/{slug}/
    template:  tag
  /newsletter/:
    data:      tag.newsletter
    filter:    tag:newsletter
    permalink: /newsletter/{slug}/
    template:  tag

taxonomies:
  tag: /tags/{slug}/